import { NextResponse } from "next/server"
import { getAuthUser } from "@/lib/auth"
import { createServiceClient } from "@/lib/supabase/server"
import { MindStudioAgent } from "@mindstudio-ai/agent"

export const maxDuration = 60

const agent = new MindStudioAgent()

interface ChatMessage {
  role: "user" | "assistant"
  content: string
}

interface ChatRequest {
  siteId: string
  message: string
  currentPrompt: string
  chatHistory: ChatMessage[]
}

interface PromptVersion {
  prompt: string
  summary: string
  created_at: string
}

export async function POST(req: Request) {
  try {
    const user = await getAuthUser()
    const supabase = createServiceClient()
    const body: ChatRequest = await req.json()

    // Verify site ownership
    const { data: site } = await supabase
      .from("sites")
      .select("id, context_files")
      .eq("id", body.siteId)
      .eq("user_id", user.id)
      .single()

    if (!site) {
      return NextResponse.json({ error: "Not found" }, { status: 404 })
    }

    // Handle website scan if message contains a URL
    let scanContext = ""
    const urlMatch = body.message.match(/https?:\/\/[^\s]+/)
    if (urlMatch) {
      try {
        const scrapeResult = await agent.scrapeUrl({
          url: urlMatch[0],
          pageOptions: {
            onlyMainContent: true,
            screenshot: false,
            waitFor: 0,
            replaceAllPathsWithAbsolutePaths: false,
            headers: {},
            removeTags: ["nav", "footer", "aside"],
            mobile: false,
          },
        })
        const text =
          typeof scrapeResult.content === "string"
            ? scrapeResult.content
            : Array.isArray(scrapeResult.content)
              ? scrapeResult.content.join("\n")
              : scrapeResult.content?.text || ""
        scanContext = `\n\nSCRAPED WEBSITE CONTENT (from ${urlMatch[0]}):\n${text.slice(0, 8000)}`
      } catch {
        scanContext = "\n\n[Website scan failed — could not access that URL.]"
      }
    }

    // Build conversation history
    const conversationHistory = body.chatHistory
      .slice(-10)
      .map((msg) => `${msg.role === "user" ? "User" : "Assistant"}: ${msg.content}`)
      .join("\n\n")

    const systemPrompt = `You are a writing prompt editor for inkpop, an AI blog platform. The user has a writing prompt that controls how their blog posts are generated by AI. Your job is to help them improve it.

CURRENT WRITING PROMPT:
---
${body.currentPrompt || "[Empty — no prompt yet]"}
---
${scanContext}

## What You Can Do
- Analyze the prompt and suggest specific, actionable improvements
- Rewrite the prompt or sections of it based on user requests
- Add new sections (audience, tone, structure, SEO rules, content types, etc.)
- Incorporate information from scraped websites into the prompt
- Answer questions about what makes a good writing prompt

## Rules
- When you make changes to the prompt, return the COMPLETE updated prompt in the "updatedPrompt" field
- Keep prompts under 3000 characters — be concise and actionable
- Write the prompt as direct instructions to an AI blog writer (second person: "Write in a...", "Target...", "Always...")
- Use markdown formatting (headers, bullets, bold) for readability
- Every sentence should give the AI writer actionable guidance — no fluff
- If the user's message doesn't require prompt changes, omit "updatedPrompt"
- Include a short "changeSummary" (under 60 chars) describing what you changed

## Good Prompt Sections
A comprehensive writing prompt typically covers:
- **Topic & niche**: What the blog is about, its angle/perspective
- **Audience**: Who reads it, their expertise level, what they care about
- **Voice & tone**: Formality, humor, personality traits
- **Content types**: Post formats (how-tos, comparisons, listicles, etc.)
- **Structure**: Word count preferences, section patterns, formatting rules
- **Rules**: Banned phrases, terminology preferences, things to always/never do

You don't need to add all sections at once — suggest improvements incrementally based on what's missing.`

    const fullPrompt = `${systemPrompt}

CONVERSATION SO FAR:
${conversationHistory || "[Start of conversation]"}

USER'S LATEST MESSAGE:
${body.message}

---

Respond with a JSON object:
- "reply": your conversational response (string, use markdown)
- "updatedPrompt": (optional) the complete new prompt text if you made changes
- "changeSummary": (optional) short description of what changed, under 60 chars

Return ONLY the JSON object, no markdown code blocks.`

    const { content } = await agent.generateText({
      message: fullPrompt,
      structuredOutputType: "json",
      structuredOutputExample: JSON.stringify({
        reply: "I've updated your prompt to include audience details...",
        updatedPrompt: "# Blog Writing Instructions\n\n## Topic\nThis blog covers...",
        changeSummary: "Added audience section",
      }),
    })

    let response: { reply: string; updatedPrompt?: string; changeSummary?: string }
    try {
      response = JSON.parse(content)
    } catch {
      response = { reply: content }
    }

    // Auto-save prompt and version if updated
    if (response.updatedPrompt) {
      // Save the new prompt
      const meta = (site.context_files as { versions?: PromptVersion[] } | null) || {}
      const versions = meta.versions || []

      // Add new version (keep last 20)
      versions.push({
        prompt: response.updatedPrompt,
        summary: response.changeSummary || "Updated via chat",
        created_at: new Date().toISOString(),
      })
      if (versions.length > 20) versions.splice(0, versions.length - 20)

      await supabase
        .from("sites")
        .update({
          writing_prompt: response.updatedPrompt,
          context_files: { versions },
        })
        .eq("id", body.siteId)
    }

    return NextResponse.json(response)
  } catch {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
  }
}
